### ISSUE TITLE
Where does it stores the secretes ?

### ISSUE THREAD

**Issue by vadorvatsal** [JeNeSuisPasDave/authenticator#12]
I want to make sure secrete is secure enough that no one will attempt to access without my permission.

**Comment by JeNeSuisPasDave** [comment]
They are stored in ~/.authenticator/authenticator.data. Permissions are set such that only the user can read or write the file.

That's true for macOS and likely true for Linux or any Unix. I'm not sure about the ACLs on Windows.

The permissions are a function of the location being within the user's home directory, and assuming the default permissions assigned to files created under the home directory. The program is not explicity setting permissions or ACLs.
