### ISSUE TITLE
Ability to export list of secret keys from authenticator.data

### ISSUE THREAD

**Issue by s3170** [JeNeSuisPasDave/authenticator#8]
It would be great if this app can export a list of the secret keys contained in the authenticator.data file.

**Comment by JeNeSuisPasDave** [comment]
I assume that you closed this because you found the "-vv" option of the list command.

:-)

**Comment by s3170** [comment]
Yes, I found it. Much appreciated!

**Comment by drzraf** [comment]
Would be great to provide a format like
`otpauth://totp/foo%3Abar%3Abaz%3Aprovider?secret=xxxx&algorithm=SHA1&digits=N&period=NN`

Would make it importable by FreeOTP+ & co out of the box.

Workaround:
`authenticator list -vv | sed 's/.*: //' | while true; do read id || break; read secret; read tb; read length; read; echo "otpauth://totp/$(urlencode "$id")?secret=$secret&algorithm=SHA1&digits=$length&period=$tb"; done`
